package edu.gatech.m1ndbl33d;

import static org.junit.Assert.assertEquals;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.List;

import edu.gatech.m1ndbl33d.controller.EnemyEngine;
import edu.gatech.m1ndbl33d.model.Antivirus;
import edu.gatech.m1ndbl33d.model.Enemy;
import edu.gatech.m1ndbl33d.model.Firewall;

/**
 * M5: Enemies must be able to die. This test will test the death of an enemy.
 */
@RunWith(AndroidJUnit4.class)
public class EnemyDiesTest {
    @Test
    public void death() {
        // List of enemies randomly generated by the app
        EnemyEngine.initializeEnemy();
        int enemyCount = EnemyEngine.getCurrentEnemies().size();
        List<Enemy> currentEnemies = EnemyEngine.getCurrentEnemies();
        EnemyEngine.getCurrentEnemies().get(0).setCurrentHealth(0);
        EnemyEngine.removeEnemy(0, true);
        int newEnemyCount = EnemyEngine.getCurrentEnemies().size();
        assertEquals(enemyCount - 1, newEnemyCount);

        EnemyEngine.addEnemy(new Antivirus());
        EnemyEngine.addEnemy(new Firewall());
        EnemyEngine.addEnemy(new Firewall());
        EnemyEngine.removeEnemy(0, true);
        EnemyEngine.removeEnemy(1, true);
        int thirdEnemyCount = EnemyEngine.getCurrentEnemies().size();
        assertEquals(thirdEnemyCount, newEnemyCount + 1);
    }
}
